name: service_connect
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bot_toast: ^4.1.3
  injectable: ^2.5.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  dartz: ^0.10.1
  get_it: ^8.0.0
  freezed_annotation: ^2.4.4
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svgs/
  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
